---
- name: create group
  ansible.builtin.group:
    name: "{{ appuser }}"
    state: present

- name: Create user with home and bash shell
  ansible.builtin.user:
    name: "{{ appuser }}"
    group: "{{ appuser }}"
    home: "/home/{{ appuser }}"
    shell: /bin/bash
    state: present
    create_home: true
    password: "{{ testCredentials | password_hash('sha512') }}"
  register: create_appuser_result

- name: Debug user creation result for appuser
  ansible.builtin.debug:
    var: create_appuser_result

- name: create group2
  ansible.builtin.group:
    name: "{{ suppuser }}"
    state: present

- name: Create user2 with home and bash shell
  ansible.builtin.user:
    name: "{{ suppuser }}"
    group: "{{ suppuser }}"
    home: "/home/{{ suppuser }}"
    shell: /bin/bash
    state: present
    create_home: true
    password: "{{ testCredentials2 | password_hash('sha512') }}"
  register: create_suppuser_result

- name: Debug user2 creation result for suppuser
  ansible.builtin.debug:
    var: create_suppuser_result
