---
- name: Create /apps/bin with mode 755
  ansible.builtin.file:
    path: "/{{ appuser }}/apps/bin"
    state: directory
    mode: '0755'
    recurse: true

- name: Create /apps/logs with mode 755
  ansible.builtin.file:
    path: "/{{ appuser }}/apps/logs"
    state: directory
    mode: '0755'
    recurse: true

- name: Create /apps/archivals with mode 755
  ansible.builtin.file:
    path: "/{{ appuser }}/apps/archivals"
    state: directory
    mode: '0755'
    recurse: true
