---
- name: Set ACL for {{ appuser }} user and group on /{{ appuser }}/apps/bin
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/bin"
    entity: "{{ appuser }}"
    etype: user
    permissions: rwx
    state: present

- name: Set ACL for {{ appuser }} group on /{{ appuser }}/apps/bin
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/bin"
    entity: "{{ appuser }}"
    etype: group
    permissions: rx
    state: present

- name: Set ACL for {{ appuser }} user on /{{ appuser }}/apps/logs
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/logs"
    entity: "{{ appuser }}"
    etype: user
    permissions: rwx
    state: present

- name: Set ACL for {{ appuser }} group on /{{ appuser }}/apps/logs
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/logs"
    entity: "{{ appuser }}"
    etype: group
    permissions: rx
    state: present

- name: Set ACL for {{ appuser }} user on /{{ appuser }}/apps/archivals
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/archivals"
    entity: "{{ appuser }}"
    etype: user
    permissions: rwx
    state: present

- name: Set ACL for {{ appuser }} group on /{{ appuser }}/apps/archivals
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/archivals"
    entity: "{{ appuser }}"
    etype: group
    permissions: rx
    state: present

- name: Set ACL for {{ suppuser }} user on /{{ appuser }}/apps/bin
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/bin"
    entity: "{{ suppuser }}"
    etype: user
    permissions: rx
    state: present

- name: Set ACL for {{ suppuser }} group on /{{ appuser }}/apps/bin
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/bin"
    entity: "{{ suppuser }}"
    etype: group
    permissions: rx
    state: present

- name: Set ACL for {{ suppuser }} user on /{{ appuser }}/apps/logs
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/logs"
    entity: "{{ suppuser }}"
    etype: user
    permissions: rx
    state: present

- name: Set ACL for {{ suppuser }} group on /{{ appuser }}/apps/logs
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/logs"
    entity: "{{ suppuser }}"
    etype: group
    permissions: rx
    state: present

- name: Set ACL for {{ suppuser }} user on /{{ appuser }}/apps/archivals
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/archivals"
    entity: "{{ suppuser }}"
    etype: user
    permissions: rx
    state: present

- name: Set ACL for {{ suppuser }} group on /{{ appuser }}/apps/archivals
  ansible.posix.acl:
    path: "/{{ appuser }}/apps/archivals"
    entity: "{{ suppuser }}"
    etype: group
    permissions: rx
    state: present
