---
- name: Create SSH directory
  become: true
  become_user: "{{ appuser }}"
  ansible.builtin.file:
    path: "/home/{{ appuser }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ appuser }}"
    group: "{{ appuser }}"

- name: Create empty known_hosts file
  become: true
  become_user: "{{ appuser }}"
  ansible.builtin.copy:
    dest: "/home/{{ appuser }}/.ssh/known_hosts"
    content: ""
    owner: "{{ appuser }}"
    group: "{{ appuser }}"
    mode: '0644'
    force: false

- name: Create empty authorized_keys file
  become: true
  become_user: "{{ appuser }}"
  ansible.builtin.copy:
    dest: "/home/{{ appuser }}/.ssh/authorized_keys"
    content: ""
    owner: "{{ appuser }}"
    group: "{{ appuser }}"
    mode: '0644'
    force: false

- name: Create empty .bashrc file
  become: true
  become_user: "{{ appuser }}"
  ansible.builtin.copy:
    dest: "/home/{{ appuser }}/.bashrc"
    content: ""
    owner: "{{ appuser }}"
    group: "{{ appuser }}"
    mode: '0644'
    force: false

- name: Create empty fstab file
  become: true
  become_user: "{{ appuser }}"
  ansible.builtin.copy:
    dest: "/etc/fstab"
    content: ""
    owner: "{{ appuser }}"
    group: "{{ appuser }}"
    mode: '0644'
    force: false
